<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vyrazu66-ThinkCentre-M70t" failures="2" tests="23" name="Default test" time="31.173" errors="0" timestamp="2023-07-21T10:44:07 IST">
  <testcase classname="Testng.FacebookTest" name="test_title" time="0.009"/>
  <testcase classname="Testng.FacebookTest" name="googleLogotest" time="0.1"/>
  <testcase classname="Testng.FacebookTest" name="Linktest" time="0.034"/>
  <testcase classname="Testng.FacebookTest" name="test4" time="0.001"/>
  <testcase classname="Testng.FacebookTest" name="test5" time="0.001"/>
  <testcase classname="Testng.FacebookTest" name="test6" time="0.001"/>
  <testcase classname="Testng.TestNgFeatures" name="loginTest" time="0.001"/>
  <testcase classname="Testng.TestNgFeatures" name="HomePageTest" time="0.001"/>
  <testcase classname="Testng.TestNgFeatures" name="RegistationPage" time="0.002"/>
  <testcase classname="Testng.TestNgFeatures" name="searchpageTest" time="0.001"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.0"/>
  <testcase classname="Testng.InvocationCountTest" name="sum" time="0.001"/>
  <testcase classname="Testng.ExceptionTimeOutTest" name="infiniteloopTest" time="0.006">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method Testng.ExceptionTimeOutTest.infiniteloopTest() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method Testng.ExceptionTimeOutTest.infiniteloopTest() didn't finish within the time-out 2
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:739)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method Testng.ExceptionTimeOutTest.infiniteloopTest() didn't finish within the time-out 2
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
... 22 more
]]>
    </failure>
  </testcase> <!-- infiniteloopTest -->
  <testcase classname="Testng.ExceptionTimeOutTest" name="test1" time="0.001"/>
  <testcase classname="Testng.GoogletitleTest" name="test_title" time="0.011">
    <failure type="java.lang.AssertionError" message="title is not matched expected [Google789] but found [Google]">
      <![CDATA[java.lang.AssertionError: title is not matched expected [Google789] but found [Google]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Testng.GoogletitleTest.test_title(GoogletitleTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test_title -->
</testsuite> <!-- Default test -->
